### ISSUE TITLE
Clouds overexposed

### ISSUE THREAD

**Issue by WazWaz** [WazWaz/EnvironmentalVisualEnhancements#11]
Note how much more overexposed the clouds are in map view as opposed to how they look in flight mode and in the tracking station in scaled space. I tested on Default EVE cfgs and SVE and both are extremely overexposed.

(originally reported by @Galileo88)

**Comment by Galileo88** [comment]
This issue is not with EVE, I found. It's with the stock game having the Sun's intensity set very high. Using Kopernicus, I can adjust the intensity in scaled space and everything looks right. I will just include a kopernicus cfg to fix it. Most people download it anyway to get rings for Jool or for OPM. So, at least this mystery is solved.
